# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './untitled.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(790, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.request = QtWidgets.QWidget()
        self.request.setObjectName("request")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.request)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableWidget_request = QtWidgets.QTableWidget(self.request)
        self.tableWidget_request.setRowCount(2)
        self.tableWidget_request.setColumnCount(2)
        self.tableWidget_request.setObjectName("tableWidget_request")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_request.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_request.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_request.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_request.setHorizontalHeaderItem(1, item)
        self.tableWidget_request.horizontalHeader().setVisible(True)
        self.tableWidget_request.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_request.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_request.verticalHeader().setVisible(False)
        self.tableWidget_request.verticalHeader().setStretchLastSection(False)
        # self.tableWidget_request.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.gridLayout_2.addWidget(self.tableWidget_request, 0, 0, 1, 3)
        self.button_add_request = QtWidgets.QPushButton(self.request)
        self.button_add_request.setObjectName("button_add_request")
        self.gridLayout_2.addWidget(self.button_add_request, 2, 0, 1, 1)
        self.button_edit_request = QtWidgets.QPushButton(self.request)
        self.button_edit_request.setObjectName("button_edit_request")
        self.gridLayout_2.addWidget(self.button_edit_request, 2, 1, 1, 1)
        self.button_delete_request = QtWidgets.QPushButton(self.request)
        self.button_delete_request.setObjectName("button_delete_request")
        self.gridLayout_2.addWidget(self.button_delete_request, 2, 2, 1, 1)
        self.button_send_request = QtWidgets.QPushButton(self.request)
        self.button_send_request.setObjectName("button_send_request")
        self.gridLayout_2.addWidget(self.button_send_request, 1, 0, 1, 3)
        self.stackedWidget.addWidget(self.request)
        self.config = QtWidgets.QWidget()
        self.config.setObjectName("config")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.config)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_request_name = QtWidgets.QLabel(self.config)
        self.label_request_name.setObjectName("label_request_name")
        self.gridLayout_3.addWidget(self.label_request_name, 0, 0, 1, 1)
        self.label_template = QtWidgets.QLabel(self.config)
        self.label_template.setObjectName("label_template")
        self.gridLayout_3.addWidget(self.label_template, 1, 0, 1, 1)
        self.comboBox_request = QtWidgets.QComboBox(self.config)
        self.comboBox_request.setObjectName("comboBox_request")
        self.gridLayout_3.addWidget(self.comboBox_request, 1, 1, 1, 1)
        self.tableWidget_header_config = QtWidgets.QTableWidget(self.config)
        self.tableWidget_header_config.setRowCount(2)
        self.tableWidget_header_config.setColumnCount(2)
        self.tableWidget_header_config.setObjectName("tableWidget_header_config")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_header_config.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_header_config.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_header_config.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_header_config.setHorizontalHeaderItem(1, item)
        self.tableWidget_header_config.horizontalHeader().setVisible(True)
        self.tableWidget_header_config.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_header_config.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_header_config.verticalHeader().setVisible(False)
        self.tableWidget_header_config.verticalHeader().setStretchLastSection(False)
        self.gridLayout_3.addWidget(self.tableWidget_header_config, 2, 0, 1, 2)
        self.gridLayout_header_table = QtWidgets.QGridLayout()
        self.gridLayout_header_table.setObjectName("gridLayout_header_table")
        self.button_header_delete = QtWidgets.QPushButton(self.config)
        self.button_header_delete.setObjectName("button_header_delete")
        self.gridLayout_header_table.addWidget(self.button_header_delete, 2, 0, 1, 1, QtCore.Qt.AlignTop)
        self.button_header_add = QtWidgets.QPushButton(self.config)
        self.button_header_add.setObjectName("button_header_add")
        self.gridLayout_header_table.addWidget(self.button_header_add, 1, 0, 1, 1, QtCore.Qt.AlignBottom)
        self.gridLayout_3.addLayout(self.gridLayout_header_table, 2, 2, 1, 1)
        self.tableWidget_body_config = QtWidgets.QTableWidget(self.config)
        self.tableWidget_body_config.setRowCount(2)
        self.tableWidget_body_config.setColumnCount(2)
        self.tableWidget_body_config.setObjectName("tableWidget_body_config")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_body_config.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_body_config.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_body_config.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_body_config.setHorizontalHeaderItem(1, item)
        self.tableWidget_body_config.horizontalHeader().setVisible(True)
        self.tableWidget_body_config.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_body_config.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_body_config.verticalHeader().setVisible(False)
        self.tableWidget_body_config.verticalHeader().setStretchLastSection(False)
        self.gridLayout_3.addWidget(self.tableWidget_body_config, 3, 0, 1, 2)
        self.gridLayout_body_table = QtWidgets.QGridLayout()
        self.gridLayout_body_table.setObjectName("gridLayout_body_table")
        self.button_body_delete = QtWidgets.QPushButton(self.config)
        self.button_body_delete.setObjectName("button_body_delete")
        self.gridLayout_body_table.addWidget(self.button_body_delete, 2, 0, 1, 1, QtCore.Qt.AlignTop)
        self.button_body_add = QtWidgets.QPushButton(self.config)
        self.button_body_add.setObjectName("button_body_add")
        self.gridLayout_body_table.addWidget(self.button_body_add, 1, 0, 1, 1, QtCore.Qt.AlignBottom)
        self.gridLayout_3.addLayout(self.gridLayout_body_table, 3, 2, 1, 1)
        self.lineEdit_request_name = QtWidgets.QLineEdit(self.config)
        self.lineEdit_request_name.setObjectName("lineEdit_request_name")
        self.gridLayout_3.addWidget(self.lineEdit_request_name, 0, 1, 1, 1)
        self.button_apply_config = QtWidgets.QPushButton(self.config)
        self.button_apply_config.setObjectName("button_apply_config")
        self.gridLayout_3.addWidget(self.button_apply_config, 4, 0, 1, 2)
        self.stackedWidget.addWidget(self.config)
        self.gridLayout.addWidget(self.stackedWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 790, 22))
        self.menubar.setObjectName("menubar")
        self.menutest = QtWidgets.QMenu(self.menubar)
        self.menutest.setObjectName("menutest")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionEdit_URI = QtWidgets.QAction(MainWindow)
        self.actionEdit_URI.setObjectName("actionEdit_URI")
        self.actionShow_Log = QtWidgets.QAction(MainWindow)
        self.actionShow_Log.setObjectName("actionShow_Log")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menutest.addSeparator()
        self.menutest.addAction(self.actionEdit_URI)
        self.menutest.addAction(self.actionShow_Log)
        self.menutest.addAction(self.actionQuit)
        self.menubar.addAction(self.menutest.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget_request.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_request.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_request.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Requst name"))
        item = self.tableWidget_request.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Request info"))
        self.button_add_request.setText(_translate("MainWindow", "Add"))
        self.button_edit_request.setText(_translate("MainWindow", "Edit"))
        self.button_delete_request.setText(_translate("MainWindow", "Delete"))
        self.button_send_request.setText(_translate("MainWindow", "Send"))
        self.label_request_name.setText(_translate("MainWindow", "Request name"))
        self.label_template.setText(_translate("MainWindow", "Select template"))
        item = self.tableWidget_header_config.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_header_config.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_header_config.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Header name"))
        item = self.tableWidget_header_config.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Header value"))
        self.button_header_delete.setText(_translate("MainWindow", "-"))
        self.button_header_add.setText(_translate("MainWindow", "+"))
        item = self.tableWidget_body_config.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_body_config.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_body_config.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Body name"))
        item = self.tableWidget_body_config.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Body value"))
        self.button_body_delete.setText(_translate("MainWindow", "-"))
        self.button_body_add.setText(_translate("MainWindow", "+"))
        self.button_apply_config.setText(_translate("MainWindow", "Apply"))
        self.menutest.setTitle(_translate("MainWindow", "Options"))
        self.actionEdit_URI.setText(_translate("MainWindow", "Edit URI"))
        self.actionShow_Log.setText(_translate("MainWindow", "Show Log"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))

